#!/usr/bin/python3

import os
import sys

margin_v = 3
font_height_px = 19
FONT_WIDTH_PX = 11
FONT_SIZE = 19
HIGHLIGHTED_ROW_INDEX = 2

def make_text_image(text, width):
    out = text + ".png"
    if os.path.exists(out):
        return
    font_face = "AvantGarde-Book"
    cmd = ("convert "
           "-size " + str(width) + "x" + ""
           "" + str(font_height_px) + " "
           "xc:black -font " + font_face + " "
           "-pointsize " + str(FONT_SIZE) + " "
           " -stroke white -fill white "
           "-annotate +1+15 '" + text + ""
           "' " + out)
    os.system(cmd)

def make_digits(digits):
    imgs = []
    for i in range(len(digits)):
        d = digits[i]
        img = "digits/" + d + ".png"

        if i == HIGHLIGHTED_ROW_INDEX:
            img = img.replace(".png", "_red.png")
        imgs.append(img)

    rows = len(digits)
    cols = 1
    cmd = ("montage -background none "
           "-geometry +0+" + str(margin_v) + " "
           "-tile " + str(cols) + "x" + str(rows) + " " + " ".join(imgs) + " out.png")
    os.system(cmd)

if __name__ == "__main__":
    digits = sys.argv[1]
    make_digits(digits)
